# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Aly Chace
tagline:          'Digital Marketer in Atlanta, Ga.'
description:      'Digital Marketer in Atlanta, Ga.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Aly Chace'
  url:            https://twitter.com/mdo

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

plugins: [redcarpet,pygments.rb]
