# Dependencies
markdown:         kramdown
highlighter:      pygments

# Setup
title:            Aly Chace
tagline:          'Digital Marketer in Atlanta, Ga.'
description:      'Digital Marketer in Atlanta, Ga.'
url:              https://alychace.com
baseurl:          /

author:
  name:           'Aly Chace'
  mastodon:
    title:        "@alyc@mastodon.social"
    url:          https://mastodon.social/@alyc
  matrix:         
    title:        "@alymch:matrix.org"
    url:          https://matrix.to/#/@alymch:matrix.org
  email:         
    title:        aly@alychace.com
    url:          mailto:aly@alychace.com

# Custom vars
version:          2.1.0

permalink: /:title/

paginate: 5

plugins: [redcarpet,pygments.rb,jekyll-seo-tag,jekyll-paginate]
